### ISSUE TITLE
Search doesn't create bookmarkable link

### ISSUE THREAD

**Issue by azaroth42** [WorldHistoricalGazetteer/whgazetteer#48]
I was going to link the Christchurch search in #47 ... but you can't link to searches.

Relatedly, if I swap to Traces and then back to Places, the search term disappears.

Persistence of user input would be very handy.

**Comment by kgeographer** [comment]
Traces have been removed from the search options. The WHG implementation of the traces concept is now realized in the Place Collection feature in beta (Aug 2022). 

The interface has been updated so that search terms are persistent when navigating away to examine a particular search result; a "return to search results" link appears on the result page. Not ideal perhaps, but tricky functionality for this non-React interface that doesn't manage state very well. Open to technical suggestions, but closing for now.
